version: '2'

services:
  gitbook:
    image: a5doc/gitbook
    build: ../
    volumes:
      - .:/docs
      - gitbook_node_modules:/docs/node_modules
      # - ../../entrypoint.sh:/usr/local/bin/entrypoint.sh
    working_dir: /docs
    ports:
      - 4000:4000

volumes:
  gitbook_node_modules:
    driver: local
